config/routes.rb
Rails.application.routes.draw do

  get "/tasks", to: "tasks#index"
  get "/tasks/new", to: "tasks#new", as: 'new_task'
  post "/tasks", to: "tasks#create"
  get "/tasks/:id", to: "tasks#show", as: 'task'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy', as: 'delete'
  # resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task =  Task.create(task_params)
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title%>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed%>
  <%= f.text_field :completed%>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>All tasks</h1>

<% @tasks.each do |task| %>
  <%= link_to task.title, task_path(task) %>
  <%= link_to 'delete a task', delete_path(task), method: :delete  %>
  <%= link_to 'edit a task', edit_path(task)  %>
  <p>--------</p>
<% end %>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Enter the title</label>
  <input type="text" name="task[title]" id="title">
  <label for="details">Enter the details</label>
  <input type="text" name="task[details]" id="details">
  <label for="completed">Enter if completed</label>
  <input type="boolean" name="task[completed]" id="completed">
  <input type="submit" value="Create task">
</form>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>


<%= link_to 'Back to all tasks', tasks_path %>